
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 28 17:38:00 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 26;
  public static final int Op_aritmetico = 24;
  public static final int Llave_c = 33;
  public static final int Op_booleano = 29;
  public static final int Llave_a = 32;
  public static final int If = 12;
  public static final int T_dato = 5;
  public static final int Default = 21;
  public static final int Set = 9;
  public static final int Puts = 10;
  public static final int Else = 16;
  public static final int Break = 14;
  public static final int Corchete_c = 35;
  public static final int Corchete_a = 34;
  public static final int Proc = 22;
  public static final int Return = 13;
  public static final int While = 18;
  public static final int Int = 6;
  public static final int Cadena = 7;
  public static final int Parentesis_c = 31;
  public static final int Comentarios = 2;
  public static final int Parentesis_a = 30;
  public static final int For = 19;
  public static final int P_coma = 37;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Switch = 20;
  public static final int Incrementar = 8;
  public static final int Linea = 3;
  public static final int Dolar = 40;
  public static final int Op_atribucion = 27;
  public static final int ERROR = 41;
  public static final int Do = 17;
  public static final int Continue = 15;
  public static final int Op_logico = 25;
  public static final int Expr = 11;
  public static final int Identificador = 38;
  public static final int Op_incremento = 28;
  public static final int Numero = 39;
  public static final int Main = 36;
  public static final int Igual = 23;
  public static final int Comillas = 4;
}

